# Placeholder AI Service
# In the future, this will connect to OpenAI/Gemini APIs.

def generate_job_description(title: str) -> str:
    """
    Generates a mock job description based on the title.
    """
    return f"""
    ## Job Title: {title}
    
    **Role Overview:**
    We are seeking a talented {title} to join our dynamic team. Use your skills to make an impact!
    
    **Responsibilities:**
    - Collaborate with cross-functional teams.
    - Develop high-quality solutions.
    - Innovate and drive growth.
    
    **Requirements:**
    - Proven experience as a {title}.
    - Strong problem-solving skills.
    - Passion for technology and youth empowerment.
    
    *(Generated by AI Prototype)*
    """

def generate_skill_summary(skill_name: str) -> str:
    """
    Generates a mock skill summary.
    """
    return f"""
    ## Skill: {skill_name}
    
    **Why learn {skill_name}?**
    {skill_name} is a high-demand skill in the modern economy. Mastering it opens doors to numerous opportunities.
    
    **Learning Path:**
    1. Beginner: Basics and fundamentals.
    2. Intermediate: Real-world projects.
    3. Advanced: Expert-level optimization.
    
    *(Generated by AI Prototype)*
    """
